version: "3.9"

services:
  server:
    build: "./nodeApp"
    container_name: nodeapp
    ports:
      - "3031:9090"
    volumes:
      - ./:/nodeApp:cached
    working_dir: /nodeApp/nodeApp
    depends_on:
      - mongodb

  web:
    build: "./vueApp"
    container_name: vue-app
    ports:
      - "8080:8080"
    volumes:
      - ./:/vueApp:cached
    working_dir: /vueApp/vueApp

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
        - 27017:27017
